# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#-- global variables, can be accessed by sub-charts.
global:
  #-- the registry where the images are stored. override during runtime for other registry at global level or individual level.
  repository: ~ # provide the repo name from where images will be sourced for example bcgo
  #-- the registry where the images are stored. override during runtime for other registry at global level or individual level. default is ghcr.io
  registry: ghcr.io # ghcr.io for directly streaming from github container registry or "artifacts.developer.gov.bc.ca/github-docker-remote" for artifactory, or any other registry.
  #-- the tag of the image, it can be latest, 1.0.0 etc..., or the sha256 hash
  tag: ~
  #-- turn off autoscaling for the entire suite by setting this to false. default is true.
  autoscaling: false
  #-- global secrets, can be accessed by sub-charts.
  secrets:
    enabled: true
    databasePassword: ~
    databaseName: ~
    persist: true
    adminJWT: ~
    jwtSecret: ~
    appKeys: ~
    apiTokenSalt: ~
    transferTokenSalt: ~
    keycloakClientID: ~
    keycloakClientSecret: ~
  config:
    databaseUser: ~
    databaseClient: ~
    databaseHost: ~
    databasePort: ~
    databaseSSL: ~
    keycloakRealm: ~
    keycloakURL: ~
  #-- domain of the application, it is required, apps.silver.devops.gov.bc.ca for silver cluster and apps.devops.gov.bc.ca for gold cluster
  domain: "apps.silver.devops.gov.bc.ca" # it is apps.gold.devops.gov.bc.ca for gold cluster
  #-- the database Alias gives a nice way to switch to different databases, crunchy, patroni ... etc.
  databaseAlias: bitnamipg #uncomment when using bitnami pg and comment below.
  #databaseAlias: postgres-crunchy #uncomment when using crunchy and comment above.

#-- the components of the application, cms.
cms:
  #-- enable or disable cms
  enabled: true
  replicaCount: 1
  #-- the deployment strategy, can be "Recreate" or "RollingUpdate"
  deploymentStrategy: Recreate
  #-- autoscaling for the component. it is optional and is an object.
  autoscaling:
    #-- enable or disable autoscaling.
    enabled: false
    #-- the minimum number of replicas.
    minReplicas: 2
    #-- the maximum number of replicas.
    maxReplicas: 2
    #-- the target cpu utilization percentage, is from request cpu and NOT LIMIT CPU.
    targetCPUUtilizationPercentage: 80
  #-- vault, for injecting secrets from vault. it is optional and is an object. it creates an initContainer which reads from vault and app container can source those secrets. for referring to a working example with vault follow this link: https://github.com/bcgov/onroutebc/blob/main/charts/onroutebc/values.yaml#L171-L186
  vault:
    #-- enable or disable vault.
    enabled: false
    #-- the role of the vault. it is required, #licenseplate-prod or licenseplate-nonprod, license plate is the namespace without env
    role: ~
    #-- the vault path where the secrets live. it is required, dev/api-1, dev/api-2, test/api-1 etc...
    secretPaths:
      - dev/api-1
      - dev/api-2
      - test/api-1
      - test/api-2
      - prod/api-1
      - prod/api-2
    #-- resources specific to vault initContainer. it is optional and is an object.
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 25Mi
  #-- the service for the component. for inter namespace communication, use the service name as the hostname.
  service:
    #-- the type of the service. it can be ClusterIP, NodePort, LoadBalancer, ExternalName. ClusterIP is the default and is recommended.
    type: ClusterIP
    port: 80 # this is the service port, where it will be exposed internal to the namespace.
    targetPort: 1337 # this is container port where app listens on
  ingress:
    annotations:
      route.openshift.io/termination: "edge"
  pdb:
    enabled: false # enable it in PRODUCTION for having pod disruption budget.
    minAvailable: 1 # the minimum number of pods that must be available during the disruption budget.

frontend:
  # -- enable or disable a component deployment.
  enabled: true
  # -- the deployment strategy, can be "Recreate" or "RollingUpdate"
  deploymentStrategy: Recreate
  replicaCount: 1
  #-- autoscaling for the component. it is optional and is an object.
  autoscaling:
    #-- enable or disable autoscaling.
    enabled: false
    #-- the minimum number of replicas.
    minReplicas: 2
    #-- the maximum number of replicas.
    maxReplicas: 2
    #-- the target cpu utilization percentage, is from request cpu and NOT LIMIT CPU.
    targetCPUUtilizationPercentage: 80
  #-- the service for the component. for inter namespace communication, use the service name as the hostname.
  service:
    #-- enable or disable the service.
    enabled: true
    #-- the type of the service. it can be ClusterIP, NodePort, LoadBalancer, ExternalName. ClusterIP is the default and is recommended.
    type: ClusterIP
    #-- the ports for the service.
    ports:
      - name: http
        #-- the port for the service. the service will be accessible on this port within the namespace.
        port: 80
        #-- the container port where the application is listening on
        targetPort: 3000
        #-- the protocol for the port. it can be TCP or UDP. TCP is the default and is recommended.
        protocol: TCP
      - port: 3003
        targetPort: 3003
        protocol: TCP
        name: metrics
  ingress:
    annotations:
      route.openshift.io/termination: "edge"
  pdb:
    enabled: false # enable it in PRODUCTION for having pod disruption budget.
    minAvailable: 1 # the minimum number of pods that must be available during the disruption budget.

crunchy:
  enabled: false # make this false and bitnami-pg true to switch from crunchy to bitnami single postgis.

bitnamipg:
  enabled: true
  image:
    registry: ghcr.io
    repository: bcgov/nr-containers/bitnami/postgresql
    tag: 15.10.0
  auth:
    existingSecret: '{{ .Release.Name }}-database'
    username: ~
    database: ~
  shmVolume:
    enabled: false
  backup:
    enabled: false
    cronjob:
      containerSecurityContext: { }
      podSecurityContext:
        enabled: false
      storage:
        size: 200Mi
  primary:
    persistence:
      enabled: true
      storageClass: netapp-block-standard
      accessModes:
        - ReadWriteOnce
      size: 200Mi
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 150Mi
      limits:
        cpu: 200m
        memory: 300Mi

