{{- if .Values.cms.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cms.fullname" . }}
  labels:
    {{- include "cms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cms.service.type }}
  ports:
    - port: {{ .Values.cms.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cms.selectorLabels" . | nindent 4 }}
{{- end }}
