apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cms
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  DATABASE_PASSWORD: {{ .Values.global.secrets.databasePassword | b64enc | quote }}
  DATABASE_USER: {{ .Values.global.config.databaseUser | b64enc | quote }}
  DATABASE_NAME: {{ .Values.global.secrets.databaseName | b64enc | quote }}
  DATABASE_CLIENT: {{ .Values.global.config.databaseClient | b64enc | quote }}
  DATABASE_PORT: {{ .Values.global.config.databasePort | b64enc | quote}}
  DATABASE_HOST: {{ .Values.global.config.databaseHost | b64enc | quote}}
  DATABASE_SSL: {{ .Values.global.config.databaseSSL | b64enc | quote}}
  KEYCLOAK_REALM: {{ .Values.global.config.keycloakRealm | b64enc | quote}}
  KEYCLOAK_URL: {{ .Values.global.config.keycloakURL | b64enc | quote}}
  KEYCLOAK_CLIENT_ID: {{ .Values.global.secrets.keycloakClientID | b64enc | quote}}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.global.secrets.keycloakClientSecret| b64enc | quote}}
  ADMIN_JWT_SECRET: {{ .Values.global.secrets.adminJWT | b64enc | quote}}
  JST_SECRET: {{ .Values.global.secrets.jwtSecret | b64enc | quote}}
  API_TOKEN_SALT: {{ .Values.global.secrets.apiTokenSalt | b64enc | quote}}
  APP_KEYS: {{ .Values.global.secrets.appKeys | b64enc | quote}}
  TRANSFER_TOKEN_SALT: {{ .Values.global.secrets.transferTokenSalt| b64enc | quote}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  postgres-password: {{ .Values.global.secrets.databasePassword | b64enc | quote }}
  password: {{ .Values.global.secrets.databasePassword | b64enc | quote }}