name: Deploy to production

on:
  workflow_dispatch:
    inputs:
      pr_no:
        description: "PR or tag to deploy (default = 'test')"
        type: number
        required: false
        default: "test"

concurrency:
  # Do not interrupt previous workflows
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  deploy-prod:
    name: Deploy (prod)
    uses: ./.github/workflows/.deployer.yml
    secrets: inherit
    with:
      environment: prod
      tag: ${{ inputs.pr_no}}
      params:
        --set cms.deploymentStrategy=RollingUpdate
        --set frontend.deploymentStrategy=RollingUpdate
        --set global.autoscaling=true
        --set frontend.pdb.enabled=true
        --set cms.pdb.enabled=true
        --set cms.replicaCount=2
        --set frontend.replicaCount=2
  promote:
    name: Promote Images
    needs: [deploy-prod]
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [cms, frontend]
    timeout-minutes: 1
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ inputs.pr_no }}
          tags: prod
